#!/bin/bash

GITHUB_USER_NAME="Edimilson-Junior"
GITHUB_REPO=""

read -p "Enter the name of the GitHub repository you want to clone: " GITHUB_REPO
git clone git@github.com:"$GITHUB_USER_NAME"/"$GITHUB_REPO".git