#!/bin/bash

GITHUB_USER_NAME=""
GITHUB_REPO=""

read -p "Enter your GitHub username: " GITHUB_USER_NAME
read -p "Enter the name of the GitHub repository you want to clone: " GITHUB_REPO
git clone git@github.com:"$GITHUB_USER_NAME"/"$GITHUB_REPO".git